name: "releases-api-sync-action"
description: "Rotate Spring project releases on api.spring.io"
author: "jzheaux"
inputs:
  api-doc-url:
    description: "The URL to the project's JavaDoc; supports {version} placeholder"
    default: "https://docs.spring.io/{project}/site/docs/{version}/api/"
    required: false
  base-uri:
    description: "Base URI for the Spring Project Service"
    default: "https://api.spring.io"
    required: false
  is-antora:
    description: "Whether the reference documentation is Antora-based; defaults to true"
    default: "true"
    required: false
  name:
    description: "the project name (for example, spring-security); will use repo name if not provided"
    required: false
  reference-doc-url:
    description: "The URL to the project's reference documentation; supports {version} placeholder"
    default: "https://docs.spring.io/{project}/reference/{version}/index.html"
    required: false
  version:
    description: "The current GA version; will read gradle.properties or pom.xml if not provided"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --releases.api.uri=${{ inputs.base-uri }}
    - --releases.api.token=${{ github.token }}
    - --releases.project.name=${{ inputs.slug || github.event.repository.name }}
    - --releases.project.version=${{ inputs.version }}
    - --releases.project.apidoc.url=${{ inputs.api-doc-url }}
    - --releases.project.refdoc.url=${{ inputs.reference-doc-url }}
    - --releases.project.refdoc.antora=${{ inputs.is-antora }}