plugins {
	id "java"
	id "org.springframework.boot" version "3.5.7"
}

repositories {
	mavenCentral()
}

java {
	sourceCompatibility = '17'
}

dependencies {
	implementation(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))

	implementation("org.springframework:spring-web")
	implementation("org.springframework.boot:spring-boot-starter-json")

	testImplementation("org.springframework.boot:spring-boot-starter-test")

	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.withType(Test) {
	useJUnitPlatform()
}

tasks.named("jar") {
	enabled = false;
}

tasks.named("bootJar") {
	archiveVersion = ""
}

tasks.withType(JavaCompile) {
	options.compilerArgs = ["-parameters", "-Xlint:all"]
}